config/routes.rb
Rails.application.routes.draw do
  root 'businesses#index'  

  post 'search', :controller => :businesses, :action => :search
end

app/models/business.rb
class Business < ActiveRecord::Base
  self.primary_key = :business_id

  has_many :category_businesses
  has_many :categories, :through => :category_businesses
  
  has_many :checkins

  geocoded_by :full_address

  attr_accessor :checkins_count

  def map_link
    "http://maps.google.com/?q=#{self.latitude},#{self.longitude}"
  end

  def self.sort_with_period_and_day(day, period, k, *near_args)
    businesses = near(*near_args)
    businesses.each do |b|
      count = 0
      if !b.checkins.nil?
        b.checkins.each do |c|
          current_count = c.count(:day => day, :period => period)
          count += current_count if !current_count.nil?
        end
      end

      b.checkins_count = count
    end

    businesses.sort { |x, y| y.checkins_count <=> x.checkins_count }.take(k)
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_businesses
  has_many :businesses, :through => :category_businesses

  scope :sorted_categories, -> { order('name') }
end

app/models/category_business.rb
class CategoryBusiness < ActiveRecord::Base
  belongs_to :category
  belongs_to :business
end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  self.primary_key = 'business_id'

  belongs_to :business

  def count(opts = {})

    opts[:day] ||= Date.today.strftime("%A").to_sym
    opts[:period] ||= :morning

    checkin_info = JSON.parse(self.checkin_info)
    days_of_week = Date::DAYNAMES.map { |d| d.to_sym }
    day_index = days_of_week.index(opts[:day])
    


      count = case opts[:period]
        when :morning     then count_for_period(checkin_info, day_index, [6, 11])
        when :noon        then count_for_period(checkin_info, day_index, [12, 16])
        when :afternoon   then count_for_period(checkin_info, day_index, [17, 20])
        when :night       then count_for_period(checkin_info, day_index, [21, 24])
        else
          raise "Wrong period value"
      end

    count
  end

  private
    def count_for_period(checkin_info, day_index, range)
      count = 0

      checkin_info.each do |period, c|
        h, di = period.split('-')
        next if (di.to_i != day_index)
        count += c.to_i if h.to_i.between?(range[0], range[1])
      end

      count
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/businesses_controller.rb
require 'benchmark'

class BusinessesController < ApplicationController
  def index
    @categories = Category.sorted_categories
    @periods = [
                  ['Morning (6am - 11pm)', 'morning'], 
                  ['Noon (12pm - 16pm)', 'noon'], 
                  ['Afternoon (17pm - 20pm)', 'afternoon'], 
                  ['Night (9pm - 6am)', 'night']
                ]
    @locations = [
                    ['Place A', '35.095238,-80.779082'], 
                    ['Place B', '35.239174,-80.886314'], 
                    ['Place C', '33.508455,-112.05002'], 
                    ['Place D', '35.1997826,-80.8518372']
                  ]
  end

  def search
    @categories = Category.sorted_categories if search_params[:category_id].empty?
    @categories = [Category.find(search_params[:category_id])] unless search_params[:category_id].empty?
    @categories.map {|c| c.name}

    @location = search_params[:location].split(',').map {|x| x.to_f}
    @day_of_week = search_params[:day_of_week].to_sym
    @period = search_params[:period].downcase.to_sym
    @number_of_results = search_params[:number_of_results].to_i
    @radius = search_params[:radius].to_f


    @execution_time = Benchmark.realtime do

      @businesses = Business.sort_with_period_and_day(@day_of_week, 
                                                      @period, 
                                                      @number_of_results, 
                                                      @location, 
                                                      @radius, 
                                                      :units => :km)

      @businesses.select! {|b| (@categories & (b.categories)).size > 0}
    end
  end

  def search_params
    params.require(:search).permit([:category_id, :location, :radius, :period, :day_of_week, :number_of_results])
  end

  def form_result
	
	if (params[:category]['id'] != "")
		bus_cat_ids = CategoryBusiness.select('business_id').where("category_id = ?", params[:category]['id'])
		bus_cat  = Business.select('name').where('business_id': bus_cat_ids)
		bus_cat_names = bus_cat.map{ |b| b.name}
	end
	if ((params[:location] != "") && (params[:period] != ""))
		coords = params[:location].split(',')
		coord_1 = coords[0].gsub!('[','').to_f
		coord_2 = coords[1].gsub!(']','').to_f
		timestamp = params[:period].split(',')
		day = timestamp[0]
		period = timestamp[1].gsub!(' ','')
		integerno = timestamp[2].gsub!(' ','')
		bus_per = Business.select('name').sort_with_period_and_day(day, period, integerno.to_i, [coord_1,coord_2], 0.5, :units => :km)
		bus_per_names = bus_per.map{ |b| b.name}
	elsif ((params[:location] != "") && (params[:period] == ""))
		coords = params[:location].split(',')
		coord_1 = coords[0].gsub!('[','').to_f
		coord_2 = coords[1].gsub!(']','').to_f
		bus_loc = Business.select('name').near([coord_1,coord_2], 0.5, :units => :km)
		bus_loc_names = bus_loc.map{ |b| b.name}
	end
	if bus_cat_names && bus_per_names
		@final = bus_cat_names & bus_per_names
	elsif bus_cat_names && bus_loc_names
		@final = bus_cat_names & bus_loc_names
	elsif bus_cat_names
		@final = bus_cat_names
	elsif bus_per_names
		@final = bus_per_names
	elsif bus_loc_names
		@final = bus_loc_names	
	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
  def bootstrap_radio_button(id, name, label, checked = '')
    "<div class='radio'>
        <label>
          <input type='radio' name='#{name}' id='#{id}' #{checked}='#{checked}'>
          #{label}
        </label>
      </div>".html_safe
  end
end

app/views/businesses/_form.html.erb
<h2>Search</h2>
<hr />
<%= form_tag(search_path, method: "post") do %>

	<div class="form-group" class="field">
    	<h4>Category</h4>
    	<%= select(:search, "category_id", options_for_select(@categories.collect { |c| [ c.name, c.id ] }), { prompt: 'All Categories' }, { class: "form-control", style: "width:auto" }) %>
  	</div>

  	<div class="form-group" class="field">
  		<h4 id="location_title">Location</h4>
      <%= bootstrap_radio_button('location_auto', 'location', 'Detect automatically (device location)') %>
      <%= bootstrap_radio_button('location_manual', 'location', 'Choose Manually') %>
  		<div class="form-group" class="field">
  			<%= select_tag(:location_select, options_for_select(@locations), prompt: 'Select Place', class: "form-control", style: "width:auto") %>
  		</div>
      <%= hidden_field(:search, :location) %>
  	</div>
    <div class="form-group" class="field">
      <h4>Radius (in kilometers)</h4>
      <div class="form-group" class="field">
        <%= number_field(:search, :radius, { :min => 0.1, :step => 0.1, :value => '0.5' }) %>
      </div>
    </div>
  	<div class="form-group" class="field">
  		<h4 id="period_title">Period</h4>
  		<%= bootstrap_radio_button('period_auto', 'period', 'Detect automatically (current period)') %>
      <%= bootstrap_radio_button('period_manual', 'period', 'Choose Manually') %>
  		<div class="form-group" class="field">
  			<%= select_tag(:period_select, options_for_select(@periods), prompt: 'Select Period', class: "form-control", style: "width:auto") %>
  		</div>
      <%= hidden_field(:search, :period) %>
  	</div>

    <div class="form-group" class="field">
      <h4 id="day_of_week_title">Day of Week</h4>
      <%= bootstrap_radio_button('day_of_week_auto', 'day_of_week', 'Detect automatically (today)') %>
      <%= bootstrap_radio_button('day_of_week_manual', 'day_of_week', 'Choose Manually') %>
      <div class="form-group" class="field">
        <%= select_tag(:day_of_week_select, options_for_select(Date::DAYNAMES), prompt: 'Select Day of Week', class: "form-control", style: "width:auto") %>
      </div>
      <%= hidden_field(:search, :day_of_week) %>
    </div>

    <div class="form-group" class="field">
      <h4>Number of Results</h4>
      <div class="form-group" class="field">
        <%= number_field(:search, :number_of_results, { :min => 1, :value => '5' }) %>
      </div>
    </div>
    <br />
  	<div class="form-group" class="actions">
    	<%= submit_tag "Show Recommendations", :id => 'search', :class => "btn btn-primary" %>
  	</div>
<% end %>

app/views/businesses/form_result.html.erb
<div class="jumbotron">
	<% @final.each do |b| %>
		<%= b %><br>
	<% end %>
</div>  

app/views/businesses/index.html.erb
<div class="jumbotron">
	<%= render 'form' %>      
</div>  

app/views/businesses/search.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><b>Search Parameters</b></div>

  <table class="table">
    <tr>
    	<td>Category Name</td>
    	<td>
			<% if @categories.size > 1 %>
				All Categories
			<% else %>
				<%= @categories[0].name %>
			<% end %>
    	</td>
    </tr>
    <tr>
    	<td>Location</td>
    	<td><%= @location %></td>
    </tr>
   	<tr>
    	<td>Radius</td>
    	<td><%= @radius %>km</td>
    </tr>
   	<tr>
    	<td>Period</td>
    	<td><%= @period %></td>
    </tr>
    <tr>
    	<td>Day of Week</td>
    	<td><%= @day_of_week %></td>
    </tr>
    <tr>
    	<td>Number of Results</td>
    	<td><%= @number_of_results %></td>
    </tr>
    <tr>
        <td><b>Execution Time</b></td>
        <td><b><%= @execution_time %></b></td>
    </tr>
  </table>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><b>Businesses</b></div>

  <table class="table">
    <% if @businesses.count == 0 %>
        <tr>
            <td>No businesses found</td>
            <td></td>
            <td></td>
        </tr>
    <% else %>
        <tr>
            <td><b>Name</b></td>
            <td><b>Categories</b></td>
            <td><b>Checkins count (based on Day of Week and Period of day)</b></td>
            <td></td>
        </tr>
    <% end %>
    <% @businesses.each do |business| %>
        <tr>
            <td><%= business.name %></td>
            <td><%= business.categories.map{|c| c.name }.join(', ') %></td>
            <td><%= business.checkins_count %></td>
            <td style="text-align:right"><%= link_to 'Map', business.map_link, :class => "btn btn-primary", :target => '_blank' %></td>
        </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MobileRecommendationSystem</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">MobileRecommendationSystem</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'Home', root_path %></li>

            <!--<li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>-->
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <!--<li class="active"><a href="./">ImgSearch<span class="sr-only">(current)</span></a></li>
            <li><a href="dirUpload.php">Directory Upload</a></li>
      <li><a href="crawler.php">Crawler</a></li>-->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    
    <div class="container">
      <%= yield %>
    </div> <!-- /container --> 

    <!--<div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-3">
          <h3>Tealeaf Academy Todo</h3>
        </div>
        <div class="col-xs-9">
          
        </div>
      </div>
    </div>-->

    <%= javascript_include_tag "application" %>



</body>
</html>